export default {
  meta: {
    title: "Free Talking Photo Generator: Make Your Photo Speak",
    keywords:
      "Talking Photo, Talking Portrait, Picture Animator, Moving Pictures",
    description:
      "KreadoAI Talking Photo Tool can turn images into talking character photos. Upload portraits or choose existing photorealistic digital avatars, input text, and quickly let AI animate static pictures with realistic voiceovers.",
  },
  hero: {
    title: '<span class="light">Talking Photo </span><span>Avatar</span>',
    desc: "Using artificial intelligence (AI) technology, you only need to upload a picture to generate a talking photo digital avatar for you",
    button1: "Get Started",
    button2: "View FAQs",
  },
  features: {
    title: '<span class="light">Abundant </span>Avatars & Scene Elements',
    subTitle: "Talking Photo Avatar",
    list1: "Let the photos speak according to the character's image.",
    list2:
      "Talking photo avatars: The system provides a variety of templates, supports AI-generated photos, and supports customized uploaded photos.",
    list3: "140+ multiple languages, 1200+ character sounds.",
    sceneTitle: "Multiple Scenes Element",
  },
  sceneItems: {
    NewYear: "New Year",
    SocialMedia: "Social Media",
    Valentine: "Valentine's Day",
    Promotion: "Promotion",
    Icon: "Icon",
    Logo: "Logo",
    Button: "Button",
    Banner: "Banner",
    Flower: "Flower",
    NewsWords: "News Words",
    Guide: "Guide",
    Shape: "Shape",
  },
  aiGeneration: {
    title: '<span class="light">AI Generated </span>Talking Photo Avatars',
    desc: "The text inscription describes the character picture information, <br />and the character picture is quickly generated by submitting the inscription",
  },
  cases: {
    title:
      '<span class="light">Classic Case </span>Studies Across Industries',
    storytelling: "Storytelling",
    productIntro: "Product Introduction",
    knowledgeSharing: "Knowledge Sharing",
  },
  faq: {
    title: "FAQs",
    tail: "If you have any other questions, please contact us anytime!",
    contactSales: "Contact Us",
    questions: [
      {
        q: "What is a Talking Photo feature?",
        a: "Talking photo is a newly launched function of oral video production. Transform your still images into eloquent voices. Our cutting-edge technology animates static images with authentic human voices, seamlessly syncing with scripts provided by users.<br/><br/>With support for over 140 languages and a diverse range of 1200+ voices, Talking Photo revolutionizes visual storytelling. Your photos will not just speak, but resonate across cultures and languages, creating a truly immersive experience.",
      },
      {
        q: "What are the Possible Uses of Talking Photo?",
        a: "Users can upload photos of their favorite people to make videos, which will enhance the fun of user-made videos and create more production inspiration for users.<br/><br/>Talking Photo has versatile applications. It can enhance storytelling, making characters in books or scripts come to life visually. In education, it aids interactive learning by creating animated historical figures or educators. Businesses can utilize it for personalized customer interactions, enhancing user experience. Social media profiles become more engaging with animated avatars.<br/><br/>Additionally, it's a powerful tool for digital art, allowing artists to bring their creations to life with voice. Talking Photo opens up a world of creative possibilities across entertainment, education, business, and art.",
      },
      {
        q: "How Does Talking Photos Consume K-coins?",
        a: "The rules are the same as those for generating ordinary digital human videos.<br/>Successfully generating a 60-second video = consume 60 K-coins;<br/>Successfully generate a 90-second video = consume 90 K-coins.",
      },
      {
        q: "Is the Talking Photo Free to Use?",
        a: "Yes, free users have 3 free trial opportunities. After the trial, you need to upgrade to any version membership to get unlimited free use.",
      },
      {
        q: "Is There any Difference Between a Talking Photo and an Avatar Clone?",
        a: "Avatar cloning involves replicating your real-life appearance, expressions, and movements digitally, essentially creating a cloned version of you.<br/><br/>Talking Photo allows users to upload a custom photo (which could also be of yourself) to generate a digital persona. Unlike an avatar clone, the resulting image is static, lacking dynamic movements, but still capturing your essence in a unique and engaging way.",
      },
    ],
  },
  footer: {
    title:
      "AI Digital Human Intelligent Guide<br />Makes Your Marketing Easier!",
    button1: "Get Started",
    button2: "Contact Us",
  },
};
